name: Publish PowerShell Modules

on:
  push:
    branches:
      - main

jobs:
  publish-to-gallery:
    name: Publish to PowerShell Gallery
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish each available module
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: |
          Get-ChildItem -Directory .\src\ | ForEach-Object {

            Publish-Module -Path $_ -NuGetApiKey $env:NUGET_KEY -ErrorAction Continue
          }
